# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run tests"
  lane :test do
    # add actions here: https://docs.fastlane.tools/actions
    run_tests(workspace: "HeaderStickyTab.xcworkspace",
            devices: ["iPhone 11"],
            scheme: "HeaderStickyTab",
            code_coverage: true
            )
    xcov(
      workspace: "HeaderStickyTab.xcworkspace",
      scheme: "HeaderStickyTab",
      output_directory: "xcov_output",
      exclude_targets: "HeaderStickyTab.app"
    )
  end
end
